"use client";
import {use,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {api} from "@/lib/api";
export default function EditProfile({params}:{params:Promise<{id:string}>}){
 const {id}=use(params);const router=useRouter();const [name,setName]=useState(""),[location,setLocation]=useState(""),[titles,setTitles]=useState(""),[keywords,setKeywords]=useState(""),[exclusions,setExclusions]=useState(""),[salary,setSalary]=useState(""),[remote,setRemote]=useState(true),[hybrid,setHybrid]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let active=true;api(`/api/profiles/${id}`).then(p=>{if(!active)return;setName(p.name);setLocation(p.home_location);setTitles((p.target_titles||[]).join("\n"));setKeywords((p.priority_keywords||[]).join("\n"));setExclusions((p.exclusion_keywords||[]).join("\n"));setSalary(p.salary_target?String(p.salary_target):"");setRemote(p.remote_preferred);setHybrid(p.hybrid_preferred)}).catch(e=>setError(e.message));return()=>{active=false}},[id]);
 async function save(e:React.FormEvent){e.preventDefault();try{await api(`/api/profiles/${id}`,{method:"PUT",body:JSON.stringify({name,home_location:location,remote_preferred:remote,hybrid_preferred:hybrid,radius_miles:50,salary_min:salary?Number(salary):null,salary_target:salary?Number(salary):null,target_titles:titles.split("\n").map(x=>x.trim()).filter(Boolean),priority_keywords:keywords.split("\n").map(x=>x.trim()).filter(Boolean),exclusion_keywords:exclusions.split("\n").map(x=>x.trim()).filter(Boolean)})});router.push(`/profiles/${id}`)}catch(err){setError(err instanceof Error?err.message:"Could not update profile")}}
 return <div className="card form-card"><p className="eyebrow">PROFILE SETTINGS</p><h1>Edit Career Profile</h1><form onSubmit={save}><label>Profile name</label><input value={name} onChange={e=>setName(e.target.value)} required/><label>Home location</label><input value={location} onChange={e=>setLocation(e.target.value)}/><div className="two-input"><label><input type="checkbox" checked={remote} onChange={e=>setRemote(e.target.checked)}/> Remote roles</label><label><input type="checkbox" checked={hybrid} onChange={e=>setHybrid(e.target.checked)}/> Hybrid roles</label></div><label>Target salary</label><input type="number" value={salary} onChange={e=>setSalary(e.target.value)}/><label>Target titles, one per line</label><textarea rows={7} value={titles} onChange={e=>setTitles(e.target.value)}/><label>Priority keywords, one per line</label><textarea rows={7} value={keywords} onChange={e=>setKeywords(e.target.value)}/><label>Exclude keywords, one per line</label><textarea rows={4} value={exclusions} onChange={e=>setExclusions(e.target.value)}/>{error&&<p className="error">{error}</p>}<button>Save changes</button></form></div>;
}
